set(TALOS_FREESTANDING true)

set(TALOS_C_COMPILER i686-talos-gcc)
set(TALOS_CXX_COMPILER i686-talos-g++)

set(CMAKE_ASM_NASM_OBJECT_FORMAT elf32)

set(TALOS_CPU x86)
set(TALOS_PAGE_SIZE 4096)

execute_process(COMMAND ${TALOS_CXX_COMPILER} -print-file-name=crti.o OUTPUT_VARIABLE TALOS_CRTI OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${TALOS_CXX_COMPILER} -print-file-name=crtbegin.o OUTPUT_VARIABLE TALOS_CRTBEGIN OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${TALOS_CXX_COMPILER} -print-file-name=crtend.o OUTPUT_VARIABLE TALOS_CRTEND OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND ${TALOS_CXX_COMPILER} -print-file-name=crtn.o OUTPUT_VARIABLE TALOS_CRTN OUTPUT_STRIP_TRAILING_WHITESPACE)
